spring:
  application:
    name: w-gateway
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      profile: default
      discovery:
        enabled: true
        serviceId: w-config
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer-1-server.com:9001/eureka,http://peer-2-server.com:9002/eureka,http://peer-3-server.com:9003/eureka
server:
  port: 18080
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    # 可以通过 /actuator/gateway/routes 来列出所有的 routes
    gateway:
      enabled: true