spring:
  application:
    name: w-authservice
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      profile: default
      discovery:
        enabled: true
        serviceId: w-config
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer-1-server.com:9001/eureka,http://peer-2-server.com:9002/eureka,http://peer-3-server.com:9003/eureka
server:
  port: 40000
management:
  endpoints:
    web:
      exposure:
        include: '*'