---
spring:
  application:
    name: w-registry
  config:
    activate:
      onProfile: default
server:
  port: 9000
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF

---
spring:
  application:
    name: w-registry
  config:
    activate:
      onProfile: peer1
server:
  port: 9001
eureka:
  instance:
    hostname: peer-1-server.com
  client:
    serviceUrl:
      defaultZone: http://peer-2-server.com:9002/eureka/,http://peer-3-server.com:9003/eureka/

---
spring:
  application:
    name: w-registry
  config:
    activate:
      onProfile: peer2
server:
  port: 9002
eureka:
  instance:
    hostname: peer-2-server.com
  client:
    serviceUrl:
      defaultZone: http://peer-1-server.com:9001/eureka/,http://peer-3-server.com:9003/eureka/

---
spring:
  application:
    name: w-registry
  config:
    activate:
      onProfile: peer3
server:
  port: 9003
eureka:
  instance:
    hostname: peer-3-server.com
  client:
    serviceUrl:
      defaultZone: http://peer-1-server.com:9001/eureka/,http://peer-2-server.com:9002/eureka/