spring:
  application:
    name: w-web
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      profile: default
      discovery:
        enabled: true
        serviceId: w-config
server:
  port: 50000
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer-1-server.com:9001/eureka, http://peer-2-server.com:9002/eureka, http://peer-3-server.com:9003/eureka
management:
  endpoints:
    web:
      exposure:
        include: '*'