server:
  port: 8888
spring:
  application:
    name: wconf-server
  cloud:
    config:
      server:
        git:
          uri: ${user.home}/GitRepo/config
          default-label: master
          search-paths: wconf